# Generated by Django 5.2.4 on 2025-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_content', models.CharField(max_length=255)),
                ('types', models.CharField(blank=True, max_length=100)),
                ('to_content', models.TextField()),
            ],
        ),
    ]
