# Generated by Django 5.1.3 on 2025-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictionaryentry',
            index=models.Index(fields=['from_content'], name='dictionary__from_co_30ac01_idx'),
        ),
    ]
