# Generated by Django 5.1.3 on 2025-08-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0002_dictionaryentry_dictionary__from_co_30ac01_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dictionaryentry',
            name='dictionary__from_co_30ac01_idx',
        ),
    ]
