# Generated by Django 5.1.3 on 2025-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cards_reviewed', models.PositiveIntegerField(default=0)),
                ('cards_correct', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Flashcard Session',
                'verbose_name_plural': 'Flashcard Sessions',
                'db_table': 'flashcard_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this flashcard should appear in reviews', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, help_text='When this flashcard was last reviewed', null=True, verbose_name='Last Reviewed'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for organizing flashcards (e.g., 'animals, nature')", max_length=200),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='times_correct',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this flashcard was answered correctly', verbose_name='Times Correct'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='times_reviewed',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this flashcard has been reviewed', verbose_name='Times Reviewed'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back_text',
            field=models.TextField(help_text='The Malayalam translation/meaning to display on the back', verbose_name='Malayalam Meaning'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front_text',
            field=models.CharField(help_text='The English word to display on the front of the flashcard', max_length=255, verbose_name='English Word'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['front_text'], name='flashcard_c_front_t_32ab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['created_at'], name='flashcard_c_created_2aace2_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['is_active'], name='flashcard_c_is_acti_a122dc_idx'),
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table='flashcard_cards',
        ),
    ]
