# Generated by Django 5.1.3 on 2025-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0002_flashcardsession_alter_flashcard_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlashcardSession',
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='flashcard',
            name='flashcard_c_front_t_32ab9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='flashcard',
            name='flashcard_c_created_2aace2_idx',
        ),
        migrations.RemoveIndex(
            model_name='flashcard',
            name='flashcard_c_is_acti_a122dc_idx',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='back_text',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='front_text',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='times_correct',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='times_reviewed',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='english_word',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='malayalam_meaning',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table=None,
        ),
    ]
