# Generated by Django 5.1.3 on 2025-08-12 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_delete_flashcardsession_alter_flashcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')], default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='times_reviewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='word_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
