# Generated by Django 5.1.3 on 2025-08-21 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0005_flashcard_owner_alter_flashcard_difficulty_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='owner',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')], default=1),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['next_review'], name='flashcard_a_next_re_c7a635_idx'),
        ),
    ]
