# Generated by Django 5.1.3 on 2025-08-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0007_alter_flashcard_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flashcard',
            name='flashcard_a_next_re_c7a635_idx',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='user',
        ),
    ]
